# Generated by Django 2.2 on 2019-10-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=500)),
                ('tratamiento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteAmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('RUT', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=400)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('nombre_tarjeta', models.CharField(max_length=300)),
                ('fecha_tarjeta', models.DateField()),
                ('numero_tarjeta', models.IntegerField()),
                ('cvc_tarjeta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('especie', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('disponibilidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=200)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contrasena_usuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('horario_inicio', models.CharField(max_length=100)),
                ('horario_final', models.CharField(max_length=100)),
            ],
        ),
    ]
