# Generated by Django 2.2 on 2019-10-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='cliente_amo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='miapp.ClienteAmo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Compra'),
        ),
        migrations.AddField(
            model_name='solicitudhora',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Mascota'),
        ),
        migrations.AddField(
            model_name='solicitudhora',
            name='profesional',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Profesional'),
        ),
    ]
