# Generated by Django 2.2 on 2019-10-20 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20191019_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='compra',
        ),
        migrations.AddField(
            model_name='atencion',
            name='hora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.SolicitudHora'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nombre_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.ClienteAmo'),
        ),
    ]
